### PR TITLE
[experiment] Migrate to ascom-alpaca

### PR DESCRIPTION
**Pull request by RReverser**
As mentioned in https://github.com/jsorrell/star-adventurer-alpaca/issues/3#issuecomment-1506123149, I've been building a library / framework for ASCOM Alpaca in Rust that takes care of all the HTTP serialization, auto-discovery mechanism, logging, implements all devices types, client and server parts, leaving user to have to implement only high-level code for their device or an app.

I've now published it to crates.io as beta, and probably going to release soon as most of the stuff I wanted to cover is now done.

When looking for things to test on, this project seemed large enough to provoke curiosity so I tried porting it to use my new framework.

Some concepts are slightly different, and I had to move some helper methods into extension traits but otherwise I think this went pretty well.

It's a pretty large change and you're certainly in no way obliged to merge it, but I thought I'd open a PR to showcase the difference / usage just for demo purposes in case you're curious.

### CODE REVIEW

**Comment by RReverser** [comment]
@jsorrell Any thoughts?

**Comment by RReverser** [comment]
Ping?

**Comment by jsorrell** [comment]
Sure, I can merge it. This project is pretty dead though. I've been working on a replacement which is almost ready for pushing and uses your library. I've found a couple minor bugs which I'll submit issues for.

**Comment by RReverser** [comment]
> I've been working on a replacement which is almost ready for pushing and uses your library. I've found a couple minor bugs which I'll submit issues for.

Ah awesome, would be happy to take a look.

Mainly wanted this merged so that I have at least one public project to point to for now.

**Pull request merged**
